### PR TITLE
Added converters for .gaml files

### LINKED ISSUE #607: Generalized Analytical Markup Language
http://www.gaml.org/ spearheaded by @thermoscientificcmd is an XML based open file format for @FDA approved long-term data storage for use in electronic laboratory notebooks. It covers a wide range of instrument types.

### PR DESCRIPTION
**Pull request by Mailaender**
Closes https://github.com/eclipse/chemclipse/issues/607

### CODE REVIEW

**Comment by eselmeister** [comment]
@Mailaender You are right, it's too much work to get this things through the Eclipse IP process. Hence, let's try it at OpenChrom first.

Adjust the Automatic-Module-Name to the openchrom bundle name.

**Comment by Mailaender** [comment]
Adjusted.

**Comment by eselmeister** [comment]
@Mailaender Why have changed been applied on:

```
net.openchrom.msd.converter.supplier.mz5
net.openchrom.msd.converter.supplier.mz5.ui
```

Both bundles exists in the OpenChrom repo already as you have created them a while ago.

- https://github.com/OpenChrom/openchrom/tree/develop/openchrom/plugins/org.eclipse.chemclipse.msd.converter.supplier.mz5
- https://github.com/OpenChrom/openchrom/tree/develop/openchrom/plugins/org.eclipse.chemclipse.msd.converter.supplier.mz5.ui

They were never be a part of our ChemClipse activities. Why are the names changed from chemclipse?

**Comment by Mailaender** [comment]
That is a followup of https://github.com/OpenChrom/openchrom/pull/111 that I noticed during renaming.

**Comment by eselmeister** [comment]
@Mailaender I understand, unused/deactivated mz5 bundles from ChemClipse have been reactived here under the same open source license conditions.

**Pull request merged**
