### PR TITLE
Update ci.yml to newer Eclipse Temurin and Ubuntu version

### PR DESCRIPTION
**Pull request by Ramoonus**

### CODE REVIEW

**Comment by Mailaender** [comment]
Thanks, but no thanks. https://github.com/eclipse-chemclipse/chemclipse/pull/1577 is currently on hold.

**Comment by Ramoonus** [comment]
then it could be _eclipse-temurin-17-focal_

**Comment by Mailaender** [comment]
No, the Maven version is also pinned to @eclipse-tycho although we could use something newer there. We don't care for the Ubuntu version.

**Comment by Mailaender** [comment]
I got inspired to file https://github.com/OpenChrom/openchrom/pull/585.

**Pull request closed without merging**
