### PR TITLE
Added a Bruker BioTyper MSP file format import

### PR DESCRIPTION
**Pull request by Mailaender**
which is their data storage for library mass spectra.

### CODE REVIEW

**Comment by eselmeister** [comment]
@Mailaender Thanks for your PR. I reviewed the code. Please address the following issues:

A) plugin.xml
An export converter implementation is mandatory:
`exportConverter="net.openchrom.msd.converter.supplier.btmsp.converter.DatabaseExportConverter"`

You could use:
```
public class DatabaseExportConverter extends AbstractDatabaseExportConverter {

	private static final String DESCRIPTION = "BTMSP Library Export Converter";
	private static final String WARNING = "Export is not supported.";

	@Override
	public IProcessingInfo<File> convert(File file, IScanMSD massSpectrum, boolean append, IProgressMonitor monitor) {

		IProcessingInfo<File> processingInfo = new ProcessingInfo<>();
		processingInfo.addErrorMessage(DESCRIPTION, WARNING + file.getAbsolutePath());
		return processingInfo;
	}

	@Override
	public IProcessingInfo<File> convert(File file, IMassSpectra massSpectra, boolean append, IProgressMonitor monitor) {

		IProcessingInfo<File> processingInfo = new ProcessingInfo<>();
		processingInfo.addErrorMessage(DESCRIPTION, WARNING + file.getAbsolutePath());
		return processingInfo;
	}
}
```

B) DatabaseImportConverter Generics
Please use generic annotations where possible:
```
	@Override
	public IProcessingInfo<IMassSpectra> convert(final File file, final IProgressMonitor monitor) {

		final IProcessingInfo<IMassSpectra> processingInfo = super.validate(file);
		if(!processingInfo.hasErrorMessages()) {...

```

C) MassSpectrumImportConverter_Cattle_ITest
When using generic annotations, `@SuppressWarnings("unchecked")` is not needed.

D) OSGI
The folder seems to be misplaced in
`net.openchrom.msd.converter.supplier.btmsp.converter.io`
and plugin.xml (UI)
`src/net/openchrom/msd/converter/supplier/btmsp/converter/io/OSGI-INF/,\`

E) pom.xml
Add the btmsp feature and plugins to both pom.xml files of "features" and "plugins".

F) Copyright header
When re-using code from OpenChrom, ChemClipse or SWTChart ... new files automatically inherit the header of the original, see comment from Wayne Beaton:
https://github.com/eclipse/chemclipse/issues/407

**Comment by Mailaender** [comment]
Updated.

**Comment by eselmeister** [comment]
@Mailaender Thanks for taking care. One minor issue is left to address:

When extending the header, please use only two year marker:
Copyright (c) [initial], [update] ...

So, instead of extending the copyright by 2020:
`Copyright (c) 2015, 2018, 2020 Lablicate GmbH.`

Please replace e.g. the last update year by the current one:
`Copyright (c) 2015, 2020 Lablicate GmbH.`

**Comment by Mailaender** [comment]
Tidied up the copyright headers.

**Comment by eselmeister** [comment]
@Mailaender The commit still contains wrong header. Have a look at
`Copyright (c) 2015, 2018, 2020 Lablicate GmbH.`:

`DatabaseExportConverter.java`
`MassSpectrumImportConverter_Cattle_ITest.java `

**Comment by Mailaender** [comment]
Fixed those as well. Sorry.

**Pull request merged**
